---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openldap-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      serviceAccountName: openldap-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - image: "osixia/openldap:1.3.0"
          imagePullPolicy: IfNotPresent
          name: openldap
          ports:
            - containerPort: 389
          args:
            - --copy-service
          env:
          - name: LDAP_TLS
            valueFrom:
              configMapKeyRef:
                name: openldap-bootstrap-config
                key: LDAP_TLS
          - name: LDAP_ADMIN_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: openldap-bootstrap-config
                key: LDAP_ADMIN_PASSWORD
          - name: LDAP_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: openldap-bootstrap-config
                key: LDAP_DOMAIN
          - name: LDAP_REMOVE_CONFIG_AFTER_SETUP
            valueFrom:
              configMapKeyRef:
                name: openldap-bootstrap-config
                key: LDAP_REMOVE_CONFIG_AFTER_SETUP
          - name: DISABLE_CHOWN
            valueFrom:
              configMapKeyRef:
                name: openldap-bootstrap-config
                key: DISABLE_CHOWN
          volumeMounts:
          - name: openldap-data
            mountPath: /var/lib/ldap
          - name: openldap-data
            mountPath: /etc/ldap/slapd.d
      volumes:
      - name: openldap-data
        persistentVolumeClaim:
          claimName: openldap-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ldap-svc
spec:
  ports:
    - port: 389
      protocol: TCP
      targetPort: 389
      name: ldap
  selector:
    app: openldap
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: ldap-route
spec:
  to:
    kind: Service
    name: ldap-svc
  port:
    targetPort: ldap
