apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-bootstrap-config
  namespace: viya4
data:
  LDAP_TLS: "false"
  LDAP_ADMIN_PASSWORD: "Password123"
  LDAP_DOMAIN: "viya.com"
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
  DISABLE_CHOWN: "false"
  LDAP_USERS_CONF: |
    dn: uid=viya_admin,ou=people,dc=viya.com,dc=com
    changetype: add
    objectClass: inetOrgPerson
    objectclass: extensibleObject
    uid: viya_admin
    uidNumber: 2001
    gidNumber: 2000
    cn: administrator
    sn: Admin
    homeDirectory: /home/viya_admin
    mail: viya_admin@example.com
    distinguishedName: uid=viya_admin,ou=people,dc=viya.com,dc=com
    displayName: Viya Administrator
    userPassword: Password123
    
    dn: uid=emanuel,ou=people,dc=viya.com,dc=com
    changetype: add
    objectClass: inetOrgPerson
    objectclass: extensibleObject
    uid: emanuel
    uidNumber: 7001
    gidNumber: 1000
    cn: emanuel
    sn: Emanuel Oliveira
    distinguishedName: uid=emanuel,ou=people,dc=viya.com,dc=com
    displayName: Test User 1
    userPassword: Password123
    homeDirectory: /home/user1
    mail: emanuel.oliveira@sas.com
    
    dn: uid=willian,ou=people,dc=viya.com,dc=com
    changetype: add
    objectClass: inetOrgPerson
    objectclass: extensibleObject
    uid: willian
    uidNumber: 7002
    gidNumber: 1000
    cn: willian
    sn: Willian Rosa
    distinguishedName: uid=willian,ou=people,dc=viya.com,dc=com
    displayName: Test User 2
    userPassword: Password123
    homeDirectory: /home/user2
    mail: willian.rosa@sas.com

    dn: cn=users,ou=groups,dc=viya.com,dc=com
    changetype: add
    objectclass: groupofUniqueNames
    objectclass: extensibleObject
    gidNumber: 1000
    distinguishedName: cn=group1,ou=groups,dc=viya.com,dc=com
    uniqueMember: uid=emanuel,ou=people,dc=viya.com,dc=com
    uniqueMember: uid=willian,ou=people,dc=viya.com,dc=com
    
    dn: cn=admins,ou=groups,dc=viya.com,dc=com
    changetype: add
    objectclass: groupofUniqueNames
    objectclass: extensibleObject
    gidNumber: 2000
    distinguishedName: cn=admins,ou=groups,dc=viya.com,dc=com
    uniqueMember: uid=viya_admin,ou=people,dc=viya.com,dc=com
    uniqueMember: uid=emanuel,ou=people,dc=viya.com,dc=com
    uniqueMember: uid=willian,ou=people,dc=viya.com,dc=com
  LDAP_GROUPS_CONF: |
    dn: ou=people,dc=viya.com,dc=com
    changetype: add
    objectClass: organizationalUnit
    ou: people
    
    dn: ou=groups,dc=viya.com,dc=com
    changetype: add
    ou: groups
    description: All organizational groups
    objectclass: organizationalunit

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ldap-pv
  namespace: viya4
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/ldap"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ldap-pvc
  namespace: viya4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: viya4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
        - name: openldap
          image: osixia/openldap:1.3.0
          ports:
            - containerPort: 389
            - containerPort: 636
          envFrom:
            - configMapRef:
                name: openldap-bootstrap-config
          volumeMounts:
            - name: ldap-data
              mountPath: /var/lib/ldap
            - name: ldap-config
              mountPath: /etc/ldap/slapd.d
      volumes:
        - name: ldap-data
          persistentVolumeClaim:
            claimName: ldap-pvc
        - name: ldap-config
          persistentVolumeClaim:
            claimName: ldap-pvc
