---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: openldap-users
patch: |-
  - op: replace
    path: /data/LDAP_USERS_CONF
    value: |-
      dn: uid=viya_admin,ou=people,dc=viya,dc=com
      changetype: add
      objectClass: inetOrgPerson
      objectclass: extensibleObject
      uid: viya_admin
      uidNumber: 2001
      gidNumber: 2000
      cn: administrator
      sn: Admin
      homeDirectory: /home/viya_admin
      mail: viya_admin@example.com
      distinguishedName: uid=viya_admin,ou=people,dc=viya,dc=com
      displayName: Viya Administrator
      userPassword: Password123

      dn: uid=emanuel,ou=people,dc=viya,dc=com
      changetype: add
      objectClass: inetOrgPerson
      objectclass: extensibleObject
      uid: emanuel
      uidNumber: 7001
      gidNumber: 1000
      cn: Emanuel
      sn: Oliveira
      homeDirectory: /home/emanuel
      mail: emanuel.oliveira@sas.com
      distinguishedName: uid=emanuel,ou=people,dc=viya,dc=com
      displayName: Basic User 1
      userPassword: Password123

      dn: uid=willian,ou=people,dc=viya,dc=com
      changetype: add
      objectClass: inetOrgPerson
      objectclass: extensibleObject
      uid: willian
      uidNumber: 7002
      gidNumber: 1000
      cn: Willian
      sn: Rosa
      homeDirectory: /home/willian
      mail: willian.rosa@sas.com
      distinguishedName: uid=willian,ou=people,dc=viya,dc=com
      displayName: Basic User 2
      userPassword: Password123

      dn: cn=users,ou=groups,dc=viya,dc=com
      changetype: add
      objectclass: groupofUniqueNames
      objectclass: extensibleObject
      gidNumber: 1000
      distinguishedName: cn=users,ou=groups,dc=viya,dc=com
      uniqueMember: uid=emanuel,ou=people,dc=viya,dc=com
      uniqueMember: uid=willian,ou=people,dc=viya,dc=com

      dn: cn=admins,ou=groups,dc=viya,dc=com
      changetype: add
      objectclass: groupofUniqueNames
      objectclass: extensibleObject
      gidNumber: 2000
      distinguishedName: cn=admins,ou=groups,dc=viya,dc=com
      uniqueMember: uid=viya_admin,ou=people,dc=viya,dc=com
target:
  kind: ConfigMap
  name: openldap-bootstrap-config
